name: publish-github

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest

    env:
      config: "Release"

    steps:
      - uses: actions/checkout@v2

      # Set up .NET 5
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      # restore dependencies
      - name: Install dependencies
        run: dotnet restore

      # build project
      - name: Build
        run: dotnet build --configuration $config --no-restore

      # run tests with built project
      - name: Test
        run: dotnet test --no-restore --no-build --configuration $config

      # Publish (https://github.com/marketplace/actions/publish-nuget)
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: OData.Client/OData.Client.csproj
          NUGET_SOURCE: "source"
          INCLUDE_SYMBOLS: true
